language: python

python:
  - "3.8"

cache: pip

before_install:
  - "python setup.py install"

install:
  - pip install -r requirements.txt

script: pytest --cov=vcub_keeper --cov-config=.coveragerc --cov-report=xml 
after_success: bash <(curl -s https://codecov.io/bash)
