[calculate_distance_prompt]
# Description du tool
prompt_descrption = """Calculer la distance entre deux stations (en km) grace à
leurs coordonnées (lat, lon) Exemple d'utilisation: 
1. Cherche les coordonnées de la station "Stalingrad": df[df['station_name'] == 'STALINGRAD']
2. Chercheles coordonnées de la station "Porte de Bourgogne": df[df['station_name'] =='PORTE DE BOURGOGNE']
3. Utilise calculate_distance(lat1, lon1, lat2, lon2) avec les valeurs numériques obtenues
"""