# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.5
    - name: Install
      run: |
        python setup.py install
        pip install -r requirements.txt
    - name: Create env file
    # Création d'un fichier .env durant le process de CI
    # Cf https://github.com/armgilles/vcub_keeper/issues/65
      run: |
          touch .env
          echo KEY_API_BDX=${{ secrets.KEY_API_BDX }} >> .env
    - name: Run tests
      run: coverage run -m pytest
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
    - name: Run benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests/ --codspeed
